version: '3.1'

services:
  nginx:
    image: public.ecr.aws/nginx/nginx:1.25
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/projects/rossa-incident-ai/data/demo_samples:/home/ubuntu/projects/rossa-incident-ai/data/demo_samples
    depends_on:
      - ui

  ui:
    build: 
      context: ui
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - .env.server
    volumes:
      - ./assets:/app/assets
      - /tmp/incident-ai-demo:/tmp/incident-ai-demo
    depends_on:
      - mongo

  mongo:
    image: public.ecr.aws/docker/library/mongo:6-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
