version: '3.1'

services:
  # ui:
  #   build: 
  #     context: ui
  #   ports:
  #     - 0.0.0.0:80:80
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   env_file:
  #     - .env.server
  #   volumes:
  #     - ./assets:/app/assets

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
